# general settings
name: DMSASFFNet
model_type: DMSASFFNetModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    offset: 5
    name: DMSASFFNetTrain
    type: DMSASFFNetDataset
    dataroot_compressed: # TODO: insert path
    dataroot_reference: # TODO: insert path
    dataroot_landmark: # TODO: insert path
    dataroot_gt: # TODO: insert path
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 20
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    offset: 5
    name: DMSASFFNetTest
    type: DMSASFFNetDataset
    dataroot_compressed: # TODO: insert path
    dataroot_reference: # TODO: insert path
    dataroot_landmark: # TODO: insert path
    dataroot_gt: # TODO: insert path
    io_backend:
      type: disk

# network structures
network_g:
  type: DMSASFFNet

network_d:
  type: MultiScaleDiscriminator
  input_ch: 3
  base_ch: 64
  num_layers: 3
  num_discriminators: 4

discriminator_scales_weights:
    weights: [4, 2, 1, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: !!float 3e2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
      'relu4_4': 1
      'relu3_4': 1
      'relu2_2': 1
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 10.0
    style_weight: 1
    criterion: l2
  gan_opt:
    type: GANLoss
    gan_type: hinge
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 2.0

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 2.5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
    lpips:
      type: calculate_lpips

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2.5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
